@extends('inc.layout')

@section('content')

    <section class='menu-space'></section>

    <section class='general-styles'>
        <div class='small-container'>
            <h1>Termeni şi condiţii</h1>
            <h2>Informaţii generale</h2>
            <p>Societatea comercială care oferă spre vânzare toate produsele de pe www.masara.ro este denumită Activ7 Product SRL, înregistrată la Registrul Comerțului cu nr. J01/413/2017, CUI RO37424870, având sediul în Sancel, Strada Horea, nr.6, detinătoare a brandului Masara, înregistrat la OSIM cu nr. 175153 considerată ca fiind “Vânzător”.</p>
            <p>Folosirea acestui  site (www.masara.ro) de către orice persoană (atât fizică cât și juridică) care folosește siteul în scopul de a se informa sau de a achiziționa produsele, denumit în continuare “cumpărător”, reprezintă acordul acestuia fără limitări sau rezerve a prezentelor Termeni și Condiții.</p>
            <h2>1. Înregistrare comandă</h2>
            <p>După adăugarea produselor dorite în coș, trebuie să selectezi detaliile de facturare, metoda de plată dorită și modalitatea de livrare preferată (ridicare personală din showroom sau livrare prin curier). Nu uita să citești termenii și condițiile și să bifezi căsuța “Prin trimiterea comenzii accept termenii și condițiile Masara” înainte de a trimite comanda.   Pasul final pentru trimiterea comenzii este butonul “Trimite comanda”. La scurt timp după apăsarea acestui buton vei primi un e-mail prin care se confirmă înregistrarea comenzii.</p>
            <h2>2. Modalități de plată</h2>
            <p>2.2. Plata la punctul de lucru / showroom se poate face prin următoarele modalități: numerar (până la suma maximă de 10000 lei pentru persoane fizice / 5000 lei persoane juridice);</p>
            <h2>3. Procesare comandă</h2>
            <p>3.1. După expedierea comenzii din „Coșul de cumpărături”, în scurt timp veti fi contactat de unul dintre operatorii noștri care va stabili cu dumneavoastră detaliile legate de livrare. În urma cererii de comandă efectuate pe site, email-ul trimis este generat automat și nu este confirmarea că produsele sunt pe stoc. Termenul de livrare este de 3 zile lucrătoare de la confirmarea comenzii, pentru produsele din stoc sau minim 20 zile lucrătoare de la confirmarea comenzii, pentru produsele executate la comandă.</p>
            <p>3.2. Fotografiile produselor au caracter informativ și pot exista diferențe între acestea și produsul în sine. În cazul în care prețurile sau alte detalii referitoare la produse/promoții au fost afișate gresit, inclusiv din cauza faptului că au fost introduse greșit în baza de date, ne alocăm dreptul de a anula livrarea respectivului produs și de a anunța clientul telefonic/e-mail în cel mai scurt timp, despre eroarea apărută, dacă produsul nu s-a livrat încă, sumele achitate urmând a fi rambursate (vezi Modalități rambusare, mai jos);</p>
            <h2>4. Modalități de livrare</h2>
            <p>Livrarea produselor se face până în fața imobilului, casă / bloc. Clientul are obligația de a se asigura că, la data livrării, există persoane desemnate pentru a primi, manipula și monta produsele. Cumpărătorul are obligația de a verifica integritatea și starea produselor la livrare, în prezența transportatorului. Reclamațiile ulterioare nu sunt acceptate.</p>
            <p>4.1. Livrare prin curier (standard):</p>
            <p>Livrarea este gratuită pentru toate comenzile.</p>
            <h2>5. Comanda</h2>
            <p>5.1. Prin finalizarea comenzii, cumpărătorul consimte că toate datele furnizate de acesta, necesare procesului de cumpărare, sunt corecte, complete și adevărate la data plasării comenzii.</p>
            <p>5.2. Prin finalizarea comenzii, cumpărătorul consimte că vânzătorul (Masara) poate să îl contacteze, prin orice mijloc disponibil / agreat de vânzător, în orice situație în care este necesară contactarea cumpărătorului.</p>
            <p>5.3. Vânzătorul poate anula comanda efectuată de către cumpărător, în urma unei notificări prealabile adresate cumpărătorului, fără nicio obligație ulterioară a vreunei părți față de cealaltă sau fără ca vreo parte să poată să pretindă celeilalte daune-interese în următoarele cazuri:</p>
            <p>5.3.1. neacceptarea de către banca emitentă a cardului cumpărătorului, a tranzacției, în cazul plății online;</p>
            <p>5.3.2. invalidarea tranzacției de către procesatorul de carduri agreat de vânzător, în cazul plății online;</p>
            <p>5.3.3. datele furnizate de către client/cumpărător, pe site sunt incomplete și/sau incorecte.</p>
            <h2>6. Dreptul de retragere</h2>
            <p>6.1. Cumpărătorul are dreptul să se retragă din contract, respectiv să returneze un bun, în termen de 14 zile calendaristice, fără invocarea niciunui motiv și fără a suporta alte costuri decât cele de livrare. Astfel, potrivit OUG nr 34/2014, perioada de returnare a unui bun sau renunțare la un serviciu expiră în termen de 14 zile calendaristice de la ziua în care cumpărătorul intră în posesia fizică a bunului cumpărat. Această regulă sa aplică doar produselor existente în stoc, nu se aplică produselor executate la comandă.</p>
            <p>6.2. În cazul în care cumpărătorul decide să se retragă din contract, acesta va putea completa formularul de retur ce se regăsește la adresa https://masara.ro/formular-retur.doc , apoi îl va trimite pe adresa contact@masara.ro .</p>
            <p>6.3. În cazul în care clientul/cumpărătorul solicită retragerea din contract în cadrul termenului legal de retragere din contract, trebuie să returneze și eventualele cadouri care au însoțit produsul respectiv. În cazul în care comanda este achitată, vânzătorul va rambursa suma în maxim 14 (paisprezece) zile de la data intrării în posesie a bunurilor returnate. Suma va fi returnată după cum urmează:</p>
            <p>6.3.1. pentru comenzile achitate cu card bancar: prin restituire în contul din care a fost efectuată plata;</p>
            <p>6.3.2. pentru comenzile achitate cu OP: prin virament bancar;</p>
            <p>6.3.3. pentru comenzile achitate cu numerar în showroom / punct de lucru: prin restituire numerar în showroom sau prin restituirea contravalorii produsului în contul bancar transmis de client;</p>
            <p>6.4. Daca bunul este returnat într-o stare în care nu mai poate fi vândut ca și nou (ambalaj deschis, accesorii lipsă, bunul este deteriorat), ne rezervăm dreptul de a solicita o taxă pentru readucerea bunului în stadiul inițial, după caz, sau pentru a acoperi diferența de preț rezultată din vânzarea produsului ca second-hand sau, la solicitarea cumpărătorului, vom reexpedia bunul, cheltuielile de livrare fiind suportate de către cumpărător.</p>
            <p>6.5. Diminuarea valorii bunurilor returnate deoarece, în cazul vânzărilor la distanță cumpărătorul nu are posibilitatea de a verifica bunurile înainte de încheierea contractului, acesta are dreptul de a se retrage din contract. Din acelasi motiv, cumpărătorului i se permite să testeze și să verifice bunurile pe care le-a cumpărat în măsura în care este necesar pentru a stabili natura, caracteristicile și modul de funcționare a bunurilor.</p>
            <p>Pentru a stabili natura, caracteristicile și modul de funcționare a bunurilor, cumpărătorul trebuie să le manipuleze și să le inspecteze în același mod în care i s-ar permite să o facă într-un magazin fizic real. De exemplu: cumpărătorul poate proba un articol, dar nu îl poate purta. Cumpărătorul este responsabil doar pentru diminuarea valorii bunurilor care rezultă din manipulări altele decât cele necesare pentru determinarea naturii, calităților și funcționării bunurilor. În cazul în care cumpărătorul iși exercită dreptul de retragere după ce a utilizat bunurile intr-o măsură care depășește limita necesară stabilirii naturii, caracteristicilor și modului de funcționare a acestora, cumpărătorul  este responsabil pentru eventuala diminuare a valorii bunurilor.  Accesoriile (documente, șuruburi etc.) aflate în cutia bunului precum și ambalajul original al acestuia fac parte integrantă din bun. Ca urmare, cumpărătorul are obligația atunci când își exercită dreptul de retragere din contract să îl returneze în ambalajul original nedeteriorat, protejat prin înfoliere cu folie pentru ambalat din plastic stretch sau ambalat în cutie din carton și împreună cu toate accesoriile acestuia.</p>
            <p>Bunurile returnate ce prezintă urme de uzură (pete, zgârieturi, îndoituri, fisuri, lovituri etc.) se acceptă retur numai după aducerea lor la conformitate, implicând  costurile de igienizare, cosmetizare, reparare, înlocuire a eventualelor piese deteriorate și aducere la o formă comercială în vederea vânzării ca produs second-hand. Valorea finală se stabilește în funcție de valoarea pieselor ce trebuie înlocuite și a manoperei de recondiționare sau ca diferență dintre valoarea inițială a produsului nou și valoarea de revânzare a produsului folosit. Orice diminuare a valorii bunurilor rezultata din manipularea acestora altele decât cele necesare pentru determinarea naturii, calităților și funcționării bunurilor este în responsabilitatea cumpărătorului. Contravaloarea taxei de diminuare va fi comunicată către cumpărător la recepționarea bunurilor returnate.</p>
            <p>6.6. În cazul în care un bun comandat de către cumpărător, nu poate fi livrat de către vânzător, acesta din urmă va informa cumpărătorul asupra acestui fapt și va returna în contul cumpărătorului contravaloarea bunului și/sau serviciului, în termen de maxim 7 (șapte) zile de la data la care vânzătorul a luat la cunoștință acest fapt sau de la data la care cumpărătorul și-a exprimat în mod expres intenția de reziliere a contractului.</p>
            <p>6.7. Bunuri pentru care nu se asigură dreptul de retragere</p>
            <p>Produsele confecționate după specificațiile prezentate de consumator și/sau personalizate, în mod clar nu pot fi returnate.</p>
            <p>6.7.1. Conform OUG 130/2000 art. 10 lit. c) – “Consumatorul nu poate denunța unilateral următoarele tipuri de contracte […] c) contracte de furnizare a unor produse executate după specificațiile consumatorului sau a unor produse distinct personalizate […].”</p>
            <p>6.7.2.    Conform OUG 34/2014 art. 16 lit c) – „Sunt exceptate de la dreptul de retragere prevăzut la art. 6.1-6.6 în ceea ce privește contractele la distanță și contractele în afara spațiilor comerciale următoarele: […] c) furnizarea de produse confecționate după specificațiile prezentate de consumator sau personalizate în mod clar […].”</p>
            <h2>7. Confidențialitate</h2>
            <p>7.2. Datele cardului de plată ale cumpărătorului nu vor fi accesibile de către Masara și nici nu vor fi stocate de Masara sau de către procesatorul de plăți integrat în site, ci doar de către instituția de autorizare a tranzacției sau o altă entitate autorizată să presteze servicii de stocare date de identificare a cardului, despre a cărei identitate cumpărătorul va fi informat, anterior introducerii datelor. Entitatea autorizată să presteze servicii de stocare a datelor de card este Stripe Payments Europe, Limited The One Building 1 Grand Canal Street Lower, Dublin 2, Co. Dublin, Ireland.</p>


        </div>
    </section>
    <section class='menu-space'></section>
@stop
